apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jx7hzkyhb-go 
  janus-idp.io/tekton: jx7hzkyhb-go
  backstage.io/kubernetes-id: jx7hzkyhb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jx7hzkyhb-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml