apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jx7hzkyhb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jx7hzkyhb-go 
  name: jx7hzkyhb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jx7hzkyhb-go 
